# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2019

environment:
  matrix:
  - TOXENV: py310

build: false

install:
  - py -m pip install flask
  - py -m pip install gunicorn

test_script:
#  - cd flaskapp
  - py -m flaskapp/st.sh
