# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2019

environment:
  matrix:
  - TOXENV: py310

build: false

install:
  - py -m pip install tox

test_script:
  - py -m tox
